(function(){
  'use strict';
  const user=window.__contentAdminUser,form=document.getElementById('content-form'),select=document.getElementById('content-select'),titleInput=document.getElementById('content-title'),valueInput=document.getElementById('content-value'),list=document.getElementById('content-list'),status=document.getElementById('status'),defaults=window.APP_LEGAL_CONTENT||{};
  let currentOverrides={},savedBackups={},sessionSnapshot=null,savedRange=null,copiedFormat=null;
  function headers(json){const h={Authorization:'Bearer '+(user.admin_token||user.token||'')};if(json)h['Content-Type']='application/json';return h;}
  function message(text,isError){status.textContent=text;status.className=isError?'status error':'status';}
  async function request(url,options){const response=await fetch(url,options);if(response.status===401||response.status===403){location.replace('/original-index.html');throw new Error('انتهت جلسة الإدارة أو لا تملك صلاحية الأدمن.');}const data=await response.json();if(!response.ok||data.success===false)throw new Error(data.error||'تعذر إكمال الطلب.');return data;}
  const contentKeys=Object.keys(defaults).filter(key=>key!=='guideMap');
  function selectedDoc(){const key=select.value,fallback=defaults[key];if(!fallback)return null;const saved=currentOverrides[key]||{};return{key,title:saved.title||fallback.title,html:typeof saved.html==='string'?saved.html:fallback.html,fallback};}
  function readSnapshot(){return{title:titleInput.value,html:valueInput.innerHTML};}
  function sameSnapshot(a,b){return!!a&&!!b&&a.title===b.title&&a.html===b.html;}
  function updateUndoButton(){document.getElementById('undo-edit').disabled=sameSnapshot(sessionSnapshot,readSnapshot());}
  function startEditSession(){sessionSnapshot=readSnapshot();savedRange=null;updateUndoButton();}
  function trackEdit(){updateUndoButton();}
  function fillForm(){const doc=selectedDoc();titleInput.value=doc?doc.title:'';valueInput.innerHTML=doc?window.sanitizePlatformRichText(doc.html):'';document.getElementById('restore-backup').disabled=!savedBackups[select.value];startEditSession();}
  function renderList(){list.replaceChildren();contentKeys.forEach(key=>{const doc=selectedDocFor(key),row=document.createElement('article');row.className='item';const name=document.createElement('h3');name.textContent=doc.title;const state=document.createElement('span');state.className='muted';state.textContent=currentOverrides[key]?'معدل':'النص الأصلي';const pick=document.createElement('button');pick.type='button';pick.textContent='فتح للتعديل';pick.onclick=()=>{select.value=key;fillForm();};row.append(name,state,pick);list.append(row);});}
  function selectedDocFor(key){const saved=currentOverrides[key]||{};return{title:saved.title||defaults[key].title};}
  async function load(){const keyToKeep=select.value;try{const data=await request('/api/platform-content',{headers:headers(false)});currentOverrides={};savedBackups={};data.items.forEach(item=>{if(!item.content_key.startsWith('legal.'))return;const key=item.content_key.slice(6);try{const parsed=JSON.parse(item.content_value);if(key.startsWith('backup.')){const backupKey=key.slice(7);if(defaults[backupKey]&&typeof parsed.title==='string'&&typeof parsed.html==='string')savedBackups[backupKey]=parsed;}else if(key!=='guideMap'&&defaults[key]&&typeof parsed.title==='string'&&typeof parsed.html==='string')currentOverrides[key]=parsed;}catch(_){}});select.replaceChildren();contentKeys.forEach(key=>{const option=document.createElement('option');option.value=key;option.textContent=(currentOverrides[key]?.title||defaults[key].title)+' — '+key;select.append(option);});if(!contentKeys.length)throw new Error('تعذر تحميل النصوص الحالية من مصدرها.');select.value=contentKeys.includes(keyToKeep)?keyToKeep:contentKeys[0];fillForm();renderList();}catch(e){list.textContent=e.message;message(e.message,true);}}
  function currentValue(){return{title:titleInput.value.trim(),html:window.sanitizePlatformRichText(valueInput.innerHTML)};}
  async function putValue(key,value,label){return request('/api/admin/platform-content/legal.'+encodeURIComponent(key),{method:'PUT',headers:headers(true),body:JSON.stringify({label,value:JSON.stringify(value)})});}
  form.addEventListener('submit',async e=>{e.preventDefault();if(!confirm('هل تريد حفظ التعديل الحالي واعتماده في صفحات المنصة؟'))return;const key=select.value;try{await putValue(key,currentValue(),titleInput.value.trim());message('حُفظ النص المنسق. سيظهر في صفحات المنصة عند فتح هذا القسم.');await load();}catch(err){message(err.message,true);}});
  select.addEventListener('change',fillForm);titleInput.addEventListener('input',trackEdit);valueInput.addEventListener('input',trackEdit);
  document.getElementById('undo-edit').addEventListener('click',()=>{if(!sessionSnapshot||!confirm('هل تريد التراجع عن كل تعديلات هذه الجلسة والعودة إلى الحالة التي فتحت عليها النص؟'))return;titleInput.value=sessionSnapshot.title;valueInput.innerHTML=window.sanitizePlatformRichText(sessionSnapshot.html);updateUndoButton();});
  function rememberSelection(){const s=window.getSelection();if(s&&s.rangeCount&&valueInput.contains(s.anchorNode)&&valueInput.contains(s.focusNode))savedRange=s.getRangeAt(0).cloneRange();}
  function restoreSelection(){if(!savedRange)return false;const s=window.getSelection();s.removeAllRanges();s.addRange(savedRange);return true;}
  function blocksForRange(range){const blocks=new Set();function add(node){const el=node.nodeType===1?node:node.parentElement,block=el&&el.closest('p,div,li,h1,h2,h3,h4,h5,h6,blockquote');if(block&&valueInput.contains(block))blocks.add(block);}if(range.collapsed)add(range.startContainer);else{const walker=document.createTreeWalker(valueInput,NodeFilter.SHOW_TEXT);while(walker.nextNode()){try{if(range.intersectsNode(walker.currentNode))add(walker.currentNode);}catch(_){}}}if(!blocks.size)add(range.commonAncestorContainer);return Array.from(blocks);}
  function textNodes(range){const nodes=[],walker=document.createTreeWalker(valueInput,NodeFilter.SHOW_TEXT);while(walker.nextNode()){try{if(range.intersectsNode(walker.currentNode)&&walker.currentNode.length)nodes.push(walker.currentNode);}catch(_){}}return nodes;}
  function readFormat(range){const node=textNodes(range)[0],el=node?node.parentElement:(range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement),block=blocksForRange(range)[0]||el;if(!el)return null;const css=getComputedStyle(el),blockCss=getComputedStyle(block);return{fontWeight:parseInt(css.fontWeight,10)>=600?'bold':'normal',fontStyle:css.fontStyle==='italic'?'italic':'normal',textDecoration:css.textDecorationLine.includes('underline')?'underline':'none',color:css.color,fontSize:css.fontSize,fontFamily:css.fontFamily,textAlign:blockCss.textAlign,direction:block.getAttribute('dir')||blockCss.direction};}
  document.addEventListener('selectionchange',rememberSelection);
  document.querySelectorAll('.toolbar button').forEach(button=>button.addEventListener('mousedown',event=>event.preventDefault()));
  document.querySelectorAll('[data-command]').forEach(button=>button.addEventListener('click',()=>{valueInput.focus();restoreSelection();document.execCommand(button.dataset.command,false,button.dataset.value||null);rememberSelection();trackEdit();}));
  document.querySelectorAll('[data-block-style]').forEach(button=>button.addEventListener('click',()=>{valueInput.focus();if(!restoreSelection())return;const range=window.getSelection().getRangeAt(0);blocksForRange(range).forEach(block=>{if(button.dataset.blockStyle==='textAlign')block.style.textAlign=button.dataset.value;else block.setAttribute('dir',button.dataset.value);});rememberSelection();trackEdit();}));
  document.getElementById('copy-format').addEventListener('click',()=>{if(!restoreSelection())return;copiedFormat=readFormat(window.getSelection().getRangeAt(0));document.getElementById('paste-format').disabled=!copiedFormat;});
  document.getElementById('paste-format').addEventListener('click',()=>{if(!copiedFormat||!restoreSelection())return;const selection=window.getSelection(),range=selection.getRangeAt(0);blocksForRange(range).forEach(block=>{block.style.textAlign=copiedFormat.textAlign;block.setAttribute('dir',copiedFormat.direction==='ltr'?'ltr':'rtl');});if(!range.collapsed)textNodes(range).reverse().forEach(node=>{const start=node===range.startContainer?range.startOffset:0,end=node===range.endContainer?range.endOffset:node.length;if(end<=start)return;const selected=node.splitText(start);selected.splitText(end-start);const span=document.createElement('span');span.style.fontWeight=copiedFormat.fontWeight;span.style.fontStyle=copiedFormat.fontStyle;span.style.textDecoration=copiedFormat.textDecoration;span.style.color=copiedFormat.color;span.style.fontSize=copiedFormat.fontSize;span.style.fontFamily=copiedFormat.fontFamily;selected.parentNode.insertBefore(span,selected);span.appendChild(selected);});rememberSelection();trackEdit();});
  document.getElementById('text-color').addEventListener('input',event=>{valueInput.focus();restoreSelection();document.execCommand('foreColor',false,event.target.value);rememberSelection();trackEdit();});
  document.getElementById('text-size').addEventListener('change',event=>{valueInput.focus();restoreSelection();document.execCommand('fontSize',false,event.target.value);rememberSelection();trackEdit();});
  document.getElementById('restore-default').addEventListener('click',async()=>{const key=select.value;if(!key||!confirm('هل تريد استعادة النسخة الأصلية لهذا النص؟ سيُستبدل النص الحالي بها.'))return;try{await request('/api/admin/platform-content/legal.'+encodeURIComponent(key),{method:'DELETE',headers:headers(false)});message('تمت استعادة النص الأصلي.');await load();}catch(e){message(e.message,true);}});
  document.getElementById('save-backup').addEventListener('click',async()=>{const key=select.value;if(!key||!confirm('هل تريد حفظ نسخة الاستعادة من التعديلات الحالية؟ ستستبدل النسخة المحفوظة سابقاً لهذا النص إن وجدت.'))return;try{await putValue('backup.'+key,currentValue(),'نسخة استعادة: '+titleInput.value.trim());message('حُفظت نسخة الاستعادة، ويمكن الرجوع إليها لاحقاً.');await load();}catch(e){message(e.message,true);}});
  document.getElementById('restore-backup').addEventListener('click',async()=>{const key=select.value,backup=savedBackups[key];if(!backup){message('لا توجد نسخة استعادة محفوظة لهذا النص.',true);return;}if(!confirm('هل تريد استعادة النسخة المحفوظة؟ سيُستبدل النص الحالي بها، وتبقى النسخة الأصلية متاحة.'))return;try{await putValue(key,backup,backup.title);message('تمت استعادة النسخة المحفوظة.');await load();}catch(e){message(e.message,true);}});
  load();
})();
