import {
  Ambulance,
  Apple,
  AppWindow,
  Axe,
  Bike,
  BookOpen,
  BrickWall,
  Briefcase,
  BriefcaseMedical,
  Brush,
  Calculator,
  Camera,
  Car,
  CarFront,
  CarTaxiFront,
  Cctv,
  Clapperboard,
  Code,
  Coffee,
  Disc,
  DoorOpen,
  Droplets,
  Drum,
  Fuel,
  Gift,
  GraduationCap,
  Guitar,
  Hammer,
  Hand,
  HeartPulse,
  Hospital,
  Hotel,
  House,
  KeyRound,
  LandPlot,
  Landmark,
  Medal,
  PartyPopper,
  PawPrint,
  PaintRoller,
  Package,
  Piano,
  Pill,
  Plug,
  Ruler,
  Scale,
  School,
  Scissors,
  Shield,
  ShoppingBasket,
  ShoppingCart,
  Smile,
  Snowflake,
  Sofa,
  SprayCan,
  Sprout,
  Stethoscope,
  Store,
  Tent,
  TrafficCone,
  Trees,
  Truck,
  Utensils,
  Waves,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { GROUP_ICON } from './groupIcons';
import { SERVICE_BY_KEY } from './index';
import type { RealEstateLayerKey } from '../config';
import type { MapTarget } from '../targets';

/**
 * The icon of every service type — a drawing from the icon library, never an emoji (emoji look different on every
 * phone and cannot be tinted). Keyed by the type's key in `shared/service-types.json`; `registry.test.ts` fails when a type
 * has none, and the group's icon stands in for a type added without one.
 */
export const TYPE_ICON: Record<string, LucideIcon> = {
  fuel_stations: Fuel,
  road_barriers: TrafficCone,
  job_vacancies: Briefcase,
  schools_kindergartens: School,
  city_landmarks: Landmark,
  electrician: Zap,
  ac_technician: Snowflake,
  plumber: Droplets,
  general_maintenance: Hammer,
  painter: PaintRoller,
  Finisher: Brush,
  carpenter: Axe,
  blacksmith: Hammer,
  builder: BrickWall,
  house_cleaner: SprayCan,
  aluminum_tech: DoorOpen,
  glass_tech: AppWindow,
  car_mechanic: Car,
  car_electrician: Plug,
  tire_tech: Disc,
  car_wash: Waves,
  motorcycle_repair: Bike,
  taxi_driver: CarTaxiFront,
  delivery_services: Package,
  tow_truck: Truck,
  cctv_installer: Cctv,
  party_planner: PartyPopper,
  zaffa_bands: Drum,
  music_bands: Guitar,
  party_rental: Tent,
  home_nurse: Stethoscope,
  masseur: Hand,
  cupping_specialist: Coffee,
  nutritionist: Apple,
  truck_driver: Truck,
  security_firms: Shield,
  furniture_buyer: Sofa,
  gardener: Sprout,
  pet_care: PawPrint,
  clown_entertainer: Smile,
  online_stores: ShoppingCart,
  villas_rent: House,
  martial_arts_gymnastics: Medal,
  public_parks_recreation: Trees,
  hotels: Hotel,
  free_distribution: Gift,
  barber_shop: Scissors,
  photographers: Camera,
  video_design_ads: Clapperboard,
  pharmacies_on_call: Pill,
  taxis_on_call: CarTaxiFront,
  emergency_hospitals: Hospital,
  clinics: HeartPulse,
  doctors_on_call: BriefcaseMedical,
  ambulances_on_call: Ambulance,
  music_training: Piano,
  lawyers: Scale,
  land_surveyors: Ruler,
  real_estate_valuers: Calculator,
  private_tutors: GraduationCap,
  programmers: Code,
  car_delivery_on_call: CarFront,
  motorcycle_delivery_on_call: Bike,
  bicycle_delivery_on_call: Bike,
  student_research_assist: BookOpen,
  supermarket: ShoppingBasket,
  commercial_shops: Store,
  restaurants: Utensils,
};

/** The three property layers. */
export const PROPERTY_ICON: Record<RealEstateLayerKey, LucideIcon> = {
  rent: KeyRound,
  sale: House,
  land: LandPlot,
};

/** The icon of a service type (its own, else its group's). */
export const serviceTypeIcon = (key: string, group: keyof typeof GROUP_ICON): LucideIcon => TYPE_ICON[key] ?? GROUP_ICON[group];

/** The icon of a property kind or service type (anything unknown: the generic one). */
export function targetIconComponent(target: MapTarget | null | undefined): LucideIcon {
  if (!target) return GROUP_ICON.misc;
  if (target.kind === 'realEstate') return PROPERTY_ICON[target.layer];
  const entry = SERVICE_BY_KEY.get(target.discriminator);
  return entry ? serviceTypeIcon(entry.key, entry.group) : GROUP_ICON.misc;
}
